In [1]:
import numpy as np

In [7]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [10]:
vec = ([1,2,3])
print(vec)
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1, 2, 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
vec2= np.arange(0,15)
print(vec2)
print('')

vec3= np.arange(0,15,3)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 0  3  6  9 12]


In [16]:
vec4=np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped=vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [22]:
mat2=np.zeros([5,3])
print(mat2)
mat3=np.ones([5,2])
print(mat3)
mat4=np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
vec5=np.arange(1,6)
vec6=np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [30]:
print(mat)
print(vec)
product=np.matmul(mat,vec)
product1=np.matmul(vec,mat)
print(product)
print(product1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3]
[14 32 50]
[30 36 42]


In [33]:
#print(np.linalg.solve(mat,product))
print(np.linalg.inv(mat))

LinAlgError: Singular matrix

In [36]:
vec7 = np.array(['blue','orange','red','red','yellow',6,'Red'])
print(vec7)
print(np.unique(vec7))

['blue' 'orange' 'red' 'red' 'yellow' '6' 'Red']
['6' 'Red' 'blue' 'orange' 'red' 'yellow']


In [39]:
rand_mat = np.random.rand(5,5)
print(rand_mat)
rand_mat2 = np.random.randn(10,5)
print(rand_mat2)

[[0.5319678  0.49628457 0.35723395 0.98483666 0.18280707]
 [0.08249675 0.21554897 0.08711162 0.29469679 0.78881086]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.40291077]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]
[[ 0.56406572 -2.45308343  1.09915431  0.55334963 -1.49591135]
 [ 1.16166719  1.63220271 -1.47229194  0.78653554 -0.24907279]
 [-0.38648293 -0.2228799   0.61999108 -0.93065148 -0.03620401]
 [ 0.51615141 -0.10689888 -0.4928117   0.92656789 -0.67133962]
 [-0.70128694 -1.67902255 -0.28971144 -1.70895881  1.6213796 ]
 [ 0.46389464  0.33988367 -2.07352601 -0.14894384  0.4001852 ]
 [-1.09059488 -1.8543349  -1.0516436   2.24155284 -0.65935472]
 [-0.55633153  1.05732578  1.01161723 -1.48532755  0.32315879]
 [ 0.68596545 -0.29920126 -0.42476915 -1.15704237  1.88778817]
 [-1.45258963 -0.88460177  0.97417898  0.14045018  0.31956351]]


In [41]:
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5306853190554573
1.0830365580215529


In [42]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.029860708218788834
2.241552839848352


In [45]:
rand_vac=np.random.randn(19)
print(rand_vac)
print(rand_vac[6])

[ 0.88886435 -0.47417462  1.85659723 -3.50552666  0.19873638  0.27650385
 -0.70781721 -0.58012442  1.42402778  1.67577472 -0.31242902 -0.84127369
  1.01161015 -0.07893234  0.40065892 -0.89231348 -0.07248998  0.10466091
 -3.8277614 ]
-0.7078172086861042


In [47]:
print(rand_vac[:5])
print(rand_vac[4:9])

[ 0.88886435 -0.47417462  1.85659723 -3.50552666  0.19873638]
[ 0.19873638  0.27650385 -0.70781721 -0.58012442  1.42402778]


In [49]:
print(np.arange(0,15,3))
print(rand_vac[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.88886435 -3.50552666 -0.70781721  1.67577472  1.01161015]


In [52]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.5319678  0.49628457 0.35723395 0.98483666 0.18280707]
 [0.08249675 0.21554897 0.08711162 0.29469679 0.78881086]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.40291077]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]
0.08711161985581528
0.08711161985581528


In [54]:
print(rand_mat[0:2,1:3])

[[0.49628457 0.35723395]
 [0.21554897 0.08711162]]


In [58]:
print(rand_vac)
rand_vac[3:5] =4
print(rand_vac)
print('')
rand_vac[3:5] =[1,2]
print('')
print(rand_vac)

[ 0.88886435 -0.47417462  1.85659723  4.          4.          0.27650385
 -0.70781721 -0.58012442  1.42402778  1.67577472 -0.31242902 -0.84127369
  1.01161015 -0.07893234  0.40065892 -0.89231348 -0.07248998  0.10466091
 -3.8277614 ]
[ 0.88886435 -0.47417462  1.85659723  4.          4.          0.27650385
 -0.70781721 -0.58012442  1.42402778  1.67577472 -0.31242902 -0.84127369
  1.01161015 -0.07893234  0.40065892 -0.89231348 -0.07248998  0.10466091
 -3.8277614 ]


[ 0.88886435 -0.47417462  1.85659723  1.          2.          0.27650385
 -0.70781721 -0.58012442  1.42402778  1.67577472 -0.31242902 -0.84127369
  1.01161015 -0.07893234  0.40065892 -0.89231348 -0.07248998  0.10466091
 -3.8277614 ]


In [60]:
print(rand_mat)
rand_mat[1:3,4:5] = 0
print(rand_mat)

[[0.5319678  0.49628457 0.35723395 0.98483666 0.18280707]
 [0.08249675 0.21554897 0.08711162 0.29469679 0.78881086]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.40291077]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]
[[0.5319678  0.49628457 0.35723395 0.98483666 0.18280707]
 [0.08249675 0.21554897 0.08711162 0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]


In [62]:
sub_mat=rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:]=3
print(sub_mat)

[[0.5319678  0.49628457 0.35723395]
 [0.08249675 0.21554897 0.08711162]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [63]:
print(rand_mat)

[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]


In [64]:
sub_mat2=rand_mat[0:2,0:3].copy()
print(sub_mat2)
sub_mat2[:]=99
print(sub_mat2)
print(rand_mat)

[[3. 3. 3.]
 [3. 3. 3.]]
[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]


In [68]:
rand_vec=np.random.randn(15)
print(rand_vec)
print(rand_vec >0)
print(rand_vec[rand_vec>0])

[-2.04311228 -0.30442006  2.25062931  0.32387903 -0.09881289  0.76717318
  0.03644874  0.48889591 -0.54829103  2.12902284  0.57024548 -0.159777
  1.10163989 -0.25511907 -1.09410945]
[False False  True  True False  True  True  True False  True  True False
  True False False]
[2.25062931 0.32387903 0.76717318 0.03644874 0.48889591 2.12902284
 0.57024548 1.10163989]


In [69]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.56406572 -2.45308343  1.09915431  0.55334963 -1.49591135]
 [ 1.16166719  1.63220271 -1.47229194  0.78653554 -0.24907279]
 [-0.38648293 -0.2228799   0.61999108 -0.93065148 -0.03620401]
 [ 0.51615141 -0.10689888 -0.4928117   0.92656789 -0.67133962]
 [-0.70128694 -1.67902255 -0.28971144 -1.70895881  1.6213796 ]
 [ 0.46389464  0.33988367 -2.07352601 -0.14894384  0.4001852 ]
 [-1.09059488 -1.8543349  -1.0516436   2.24155284 -0.65935472]
 [-0.55633153  1.05732578  1.01161723 -1.48532755  0.32315879]
 [ 0.68596545 -0.29920126 -0.42476915 -1.15704237  1.88778817]
 [-1.45258963 -0.88460177  0.97417898  0.14045018  0.31956351]]
[0.56406572 1.09915431 0.55334963 1.16166719 1.63220271 0.78653554
 0.61999108 0.51615141 0.92656789 1.6213796  0.46389464 0.33988367
 0.4001852  2.24155284 1.05732578 1.01161723 0.32315879 0.68596545
 1.88778817 0.97417898 0.14045018 0.31956351]


In [70]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-2.04311228 -0.30442006  2.25062931  0.32387903 -0.09881289  0.76717318
  0.03644874  0.48889591 -0.54829103  2.12902284  0.57024548 -0.159777
  1.10163989 -0.25511907 -1.09410945]

[-2.04311228 -0.30442006 -5.          0.32387903 -0.09881289 -5.
  0.03644874  0.48889591 -0.54829103 -5.         -5.         -0.159777
 -5.         -0.25511907 -1.09410945]


In [72]:
print(rand_mat2)
np.save('saved_file_name',rand_mat2)

[[ 0.56406572 -2.45308343  1.09915431  0.55334963 -1.49591135]
 [ 1.16166719  1.63220271 -1.47229194  0.78653554 -0.24907279]
 [-0.38648293 -0.2228799   0.61999108 -0.93065148 -0.03620401]
 [ 0.51615141 -0.10689888 -0.4928117   0.92656789 -0.67133962]
 [-0.70128694 -1.67902255 -0.28971144 -1.70895881  1.6213796 ]
 [ 0.46389464  0.33988367 -2.07352601 -0.14894384  0.4001852 ]
 [-1.09059488 -1.8543349  -1.0516436   2.24155284 -0.65935472]
 [-0.55633153  1.05732578  1.01161723 -1.48532755  0.32315879]
 [ 0.68596545 -0.29920126 -0.42476915 -1.15704237  1.88778817]
 [-1.45258963 -0.88460177  0.97417898  0.14045018  0.31956351]]


In [73]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [76]:
loaded_vec=np.load('saved_file_name.npy')
loaded_zip=np.load('zipped_file_name.npz')
print(loaded_vec)
print(loaded_zip)

[[ 0.56406572 -2.45308343  1.09915431  0.55334963 -1.49591135]
 [ 1.16166719  1.63220271 -1.47229194  0.78653554 -0.24907279]
 [-0.38648293 -0.2228799   0.61999108 -0.93065148 -0.03620401]
 [ 0.51615141 -0.10689888 -0.4928117   0.92656789 -0.67133962]
 [-0.70128694 -1.67902255 -0.28971144 -1.70895881  1.6213796 ]
 [ 0.46389464  0.33988367 -2.07352601 -0.14894384  0.4001852 ]
 [-1.09059488 -1.8543349  -1.0516436   2.24155284 -0.65935472]
 [-0.55633153  1.05732578  1.01161723 -1.48532755  0.32315879]
 [ 0.68596545 -0.29920126 -0.42476915 -1.15704237  1.88778817]
 [-1.45258963 -0.88460177  0.97417898  0.14045018  0.31956351]]


In [79]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])
new_array = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]

[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]
[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]


In [83]:
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt=np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]

[[3.         3.         3.         0.98483666 0.18280707]
 [3.         3.         3.         0.29469679 0.        ]
 [0.02986071 0.93206962 0.76228002 0.99843735 0.        ]
 [0.84393075 0.28135431 0.77700889 0.47309182 0.91940095]
 [0.98607777 0.78760567 0.36827271 0.23737644 0.44566016]]
